<Project>
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningLevel>8</WarningLevel>
    <AnalysisLevel>latest</AnalysisLevel>
    <Company>BuildnBits</Company>
    <Product>BuildnBits Usage</Product>
    <Version>1.2.1</Version>
    <AssemblyInformationalVersion>1.2.1</AssemblyInformationalVersion>
    <Authors>cicalooo</Authors>
  </PropertyGroup>
</Project>
